version: "3"
services:
  client-prod:
    container_name: client-prod
    image: ciatphdev/firebase-users-admin-client:latest
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"

  server-prod:
    container_name: server-prod
    image: ciatphdev/firebase-users-admin-server:latest
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
