version: "3"
services:
  # Create React App (CRA) running on development mode
  client-dev:
    container_name: client-dev
    image: ciatphdev/firebase-users-admin-client:dev
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    networks:
      - firebase-users-admin-dev
    volumes:
      - ./client/public:/opt/client/public
      - ./client/src:/opt/client/src
    ports:
      - "3000:3000"

  # Express app running in development mode with auto reload using nodemon
  server-dev:
    container_name: server-dev
    image: ciatphdev/firebase-users-admin-server:dev
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    networks:
      - firebase-users-admin-dev
    volumes:
      - ./server/src:/opt/server/src
    ports:
      - "3001:3001"

networks:
  firebase-users-admin-dev:
    name: firebase-users-admin-dev
    external: false
