# Builds (2) separate images for the client and server

services:
  # Build Create React App (CRA) website running on nginx container
  client-prod:
    container_name: client-prod
    image: ciatphdev/firebase-users-client:latest
    restart: always
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    networks:
      - firebase-users
    ports:
      - "3000:3000"

  # Express app (backend only) that restarts itself on errors using pm2
  server-prod:
    container_name: server-prod
    image: ciatphdev/firebase-users-server:latest
    restart: always
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    networks:
      - firebase-users
    ports:
      - "3001:3001"

networks:
  firebase-users:
    name: firebase-users
    external: false
