version: "3"
services:
  # Built Create React App (CRA) website running on nginx
  client-prod:
    container_name: client-prod
    image: ciatphdev/firebase-users-admin-client:latest
    restart: always
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"

  # Express app that restarts itself on errors using pm2
  server-prod:
    container_name: server-prod
    image: ciatphdev/firebase-users-admin-server:latest
    restart: always
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
